### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by athifongoqa** [KalleHallden/FinanceAutomation#1]
Hey man! Love your YT channel!

I tried running the Finance Automation code but it gives me: 

Traceback (most recent call last):
  File "", line 48, in <module>
    account_num = row[1].split(" ")
IndexError: list index out of range

Could you please help me out?

**Comment by Majkil** [comment]
Do you have the exports/export.csv the function is looking for?

**Comment by athifongoqa** [comment]
Yes, I do.

Regards,
Athi-Enkosi Fongoqa

**Comment by athifongoqa** [comment]
> Do you have the exports/export.csv the function is looking for?

Do you have any other suggestions?
